### ISSUE TITLE
the OLED display is displayed with some broken lines while lvgl is displaying dynamically

### ISSUE THREAD

**Issue by glin00** [kisvegabor/lvgl#2974]
Describe the issue:
I am using zephyr's lvgl as GUI library with zephyr. The display which is an OLED display can be displayed ok while lvgl is displaying any static pictures(attahced good). But the OLED display is displayed with some broken lines(attached brokens) while lvgl is displaying dynamically.

If I remove  lvgl and make firmware just display dynamic pictures(ex. a full screen red , a full screen blue, then a full screen green repeatedly) the broken lines problem will not appear. In this way, I prove that the hardware is not the root cause of this problem.  

Can any one help me how to solve this problem?

To Reproduce
The following is part of prj.conf related to lvgl.

# LVGL 
CONFIG_MAIN_STACK_SIZE=32768 
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096
CONFIG_HEAP_MEM_POOL_SIZE=65536
CONFIG_LVGL_MEM_POOL_HEAP_KERNEL=y

CONFIG_LVGL=y
CONFIG_LVGL_HOR_RES_MAX=300 
CONFIG_LVGL_VER_RES_MAX=340

CONFIG_LVGL_VDB_SIZE=100
CONFIG_LVGL_BITS_PER_PIXEL=16
CONFIG_LVGL_DPI=130

#LVGL color
CONFIG_LVGL_COLOR_DEPTH_16=y
CONFIG_LVGL_COLOR_16_SWAP=y

#LVGL display
CONFIG_DISPLAY=y
CONFIG_LVGL_DISPLAY_DEV_NAME="SmallOLED"
CONFIG_LVGL_DISP_DEF_REFR_PERIOD=30

#LVGL INDEV
CONFIG_LVGL_POINTER_KSCAN=y
CONFIG_LVGL_POINTER_KSCAN_DEV_NAME="OLEDTouch"
CONFIG_LVGL_INDEV_DEF_READ_PERIOD=50
CONFIG_LVGL_INDEV_DEF_DRAG_LIMIT=10
CONFIG_LVGL_INDEV_DEF_DRAG_THROW=20
CONFIG_LVGL_INDEV_DEF_LONG_PRESS_TIME=400
CONFIG_LVGL_INDEV_DEF_LONG_PRESS_REP_TIME=100

#LVGL buffer
CONFIG_LVGL_BUFFER_ALLOC_STATIC=y

#LVGL USE options
CONFIG_LVGL_USE_ANIMATION=y
CONFIG_LVGL_USE_API_EXTENSION_V7=y
CONFIG_LVGL_USE_API_EXTENSION_V6=y
CONFIG_LVGL_USE_ARABIC_PERSIAN_CHARS=y
CONFIG_LVGL_USE_ARC=y
CONFIG_LVGL_USE_ASSERT_MEM=y
CONFIG_LVGL_USE_ASSERT_MEM_INTEGRITY=y
CONFIG_LVGL_USE_ASSERT_NULL=y
CONFIG_LVGL_USE_ASSERT_OBJ=y
CONFIG_LVGL_USE_ASSERT_STR=y
CONFIG_LVGL_USE_ASSERT_STYLE=y
CONFIG_LVGL_USE_BAR=y
CONFIG_LVGL_USE_BIDI=y
CONFIG_LVGL_USE_BLEND_MODES=y
CONFIG_LVGL_USE_BTN=y
CONFIG_LVGL_USE_BTNMATRIX=y
CONFIG_LVGL_USE_CALENDAR=y
CONFIG_LVGL_USE_CANVAS=y
CONFIG_LVGL_USE_CHART=y
CONFIG_LVGL_USE_CHECKBOX=y
CONFIG_LVGL_USE_CONT=y
CONFIG_LVGL_USE_CPICKER=y
CONFIG_LVGL_USE_DEBUG=y
CONFIG_LVGL_USE_DROPDOWN=y
CONFIG_LVGL_USE_FILESYSTEM=y
CONFIG_LVGL_USE_FONT_COMPRESSED=y
CONFIG_LVGL_USE_FONT_SUBPX=y
CONFIG_LVGL_USE_GAUGE=y
CONFIG_LVGL_USE_GPU=y
CONFIG_LVGL_USE_GROUP=y
CONFIG_LVGL_USE_IMG=y
CONFIG_LVGL_USE_IMGBTN=y
CONFIG_LVGL_USE_IMG_TRANSFORM=y 
CONFIG_LVGL_USE_KEYBOARD=y 
CONFIG_LVGL_USE_LABEL=y
CONFIG_LVGL_USE_LED=y 
CONFIG_LVGL_USE_LINE=y 
CONFIG_LVGL_USE_LINEMETER=y 
CONFIG_LVGL_USE_LIST=y 
CONFIG_LVGL_USE_MSGBOX=y 
CONFIG_LVGL_USE_OBJMASK=y 
CONFIG_LVGL_USE_OBJ_REALIGN=y 
CONFIG_LVGL_USE_OPA_SCALE=y 
CONFIG_LVGL_USE_OUTLINE=y 
CONFIG_LVGL_USE_PAGE=y 
CONFIG_LVGL_USE_PATTERN=y 
CONFIG_LVGL_USE_PERF_MONITOR=y 
CONFIG_LVGL_USE_ROLLER=y 
CONFIG_LVGL_USE_SHADOW=y 
CONFIG_LVGL_USE_SLIDER=y 
CONFIG_LVGL_USE_SPINBOX=y
CONFIG_LVGL_USE_SPINNER=y
CONFIG_LVGL_USE_SWITCH=y
CONFIG_LVGL_USE_TABLE=y
CONFIG_LVGL_USE_TABVIEW=y
CONFIG_LVGL_USE_TEXTAREA=y 
CONFIG_LVGL_USE_THEME_MATERIAL=y 
CONFIG_LVGL_USE_TILEVIEW=y 
CONFIG_LVGL_USE_VALUE_STR=y 
CONFIG_LVGL_USE_WIN=y

CONFIG_SMALL_OLED_DRIVER=y
CONFIG_APPLICATION_DEFINED_SYSCALL=y

CONFIG_LVGL_FONT_MONTSERRAT_22=y
CONFIG_LVGL_FONT_MONTSERRAT_26=y
CONFIG_LVGL_FONT_MONTSERRAT_28=y
CONFIG_LVGL_FONT_MONTSERRAT_32=y

Environment (please complete the following information):
Hardware:STM32L496AGI6P
Display: OLED display with 4 wire SPI interface.
Linux Ubuntu 20.04.3 LTS
Zephyr SDK,-0.13.0
Zephyr SHA1 ID:bb85a55
LVGL:7.6.1
![good](https://user-images.githubusercontent.com/20088622/148528516-67bade9a-3804-4ce3-b46d-fdd2a2d624b4.png)

![broken](https://user-images.githubusercontent.com/20088622/148528631-2538c6e2-f25c-4b4a-b69c-ae4ceab02eeb.png)
![broken2](https://user-images.githubusercontent.com/20088622/148528657-efcb5662-b487-4b15-859c-ea96acd67a54.png)

**Comment by kisvegabor** [comment]
Hi,

Painting the whole screen to a color is special (the simplest) case. From my experience it will be a display driver issue. (If it were an LVGL issue it'd be wrong for everyone.)

I suggest trying to draw smaller colorful rectangles on the screen with random size and position.

**Comment by glin00** [comment]
I do find one hardware issue or limitation here. As the OLED display's datasheet points out, if any pixel data is to written to display, the data's x0 and y0 and x_width and y_width all need to be even numbers, can not be odd numbers. (note:x0, y0 are the coordinates of the upper left corner of pixels data)
![image](https://user-images.githubusercontent.com/20088622/149294934-4c6c3fd5-52d8-4aa8-a639-84250efb0ecf.png)

For a test, I made two versions of firmware.  
(A)One that rejects the pixels data to be written to display when  x0 or y0 or x_width or y_width is odd.
![image](https://user-images.githubusercontent.com/20088622/149294344-930deb04-7338-46e7-8e3f-8f0c9a8a6a64.png)

(B)The other that accepts any pixels data to be written to display without checking  x0 or y0 or x_width or y_width is even or odd. 
![image](https://user-images.githubusercontent.com/20088622/149293783-ea5daa62-7365-4040-b816-a89217146138.png)

The display result is significantly better using the one (A) that rejects pixel data with odd address or width.  
Question: Since it is the OLED display's limitation which the vendor said it can not be changed, how can I modify LVGL codes so that the pixels data written to display will have  x0 and y0 and x_width and y_width are even numbers?

**Comment by kisvegabor** [comment]
It's great that found this limitation. Fortunately, it can be solved in LVGL. 
All you need to do is registering a [rounder_cb](https://docs.lvgl.io/master/porting/display.html#optional-fields).

**Comment by glin00** [comment]
it is easy to register a rounder_cb function in lvgl 7.6.1 without zephyr. But using zephyr's lvgl  7.6.1, I am still having some difficulty to find a way to do it. If I use a debugger to single step into the zephyr source code, I find the flag 'lv_initialized' is already true when the 1st instruction in main() is executed.  

Do you have any hints how to do it using  zephyr's lvgl  7.6.1?

**Comment by glin00** [comment]
@kisvegabor , can you please give some advise on the issue I posted yesderday? I know what the code to be written in rounder_cb, but I just don't know where to register rounder_cb using zephyr's lvgl.

**Comment by kisvegabor** [comment]
I think you can do it here: 
https://github.com/zephyrproject-rtos/zephyr/blob/main/lib/gui/lvgl/lvgl_display.c#L9

**Comment by LianKaFoHaLi** [comment]
> I think you can do it here: https://github.com/zephyrproject-rtos/zephyr/blob/main/lib/gui/lvgl/lvgl_display.c#L9

I have meet the same problem in my project, Accoring to the description of rounder-cb, I define my_rounder_cb() function and  register it in lv_port_disp_init(),but the problem still exist.
![微信图片_20220120192908](https://user-images.githubusercontent.com/50412488/150330558-57b2d853-1d7e-48f0-8192-55b485f16e36.png)
I print the refresh area in disp_flush(),according to the log,my_rounder_cb() function works.

![微信图片_20220120192900](https://user-images.githubusercontent.com/50412488/150331187-12292d27-8563-431d-90db-512533ff5202.png)
![微信图片_20220120192915](https://user-images.githubusercontent.com/50412488/150331213-18fc6f69-aa52-4880-b411-92a4e73f3838.png)
my lvgl version is 8.1.0,the oled driver ic is same as ”glin00“

**Comment by LianKaFoHaLi** [comment]
> @kisvegabor , can you please give some advise on the issue I posted yesderday? I know what the code to be written in rounder_cb, but I just don't know where to register rounder_cb using zephyr's lvgl.

Hi,bro,have you solved the problem yet? I have meet the same problem.The oled driver ic is RM69310.

**Comment by LianKaFoHaLi** [comment]
> I think you can do it here: https://github.com/zephyrproject-rtos/zephyr/blob/main/lib/gui/lvgl/lvgl_display.c#L9

@kisvegabor I add a rule to print data that didn't meet requirement,according to the log,my_rounder_cb() does not seem to work in some cases
![image](https://user-images.githubusercontent.com/50412488/150455865-3959b861-8698-40fa-8d3d-0a18174462af.png)
![image](https://user-images.githubusercontent.com/50412488/150456422-97af1ae8-1264-47ad-8687-cb68bdd82205.png)

**Comment by LianKaFoHaLi** [comment]
> > I think you can do it here: https://github.com/zephyrproject-rtos/zephyr/blob/main/lib/gui/lvgl/lvgl_display.c#L9
> 
> @kisvegabor I add a rule to print data that didn't meet requirement,according to the log,my_rounder_cb() does not seem to work in some cases ![image](https://user-images.githubusercontent.com/50412488/150455865-3959b861-8698-40fa-8d3d-0a18174462af.png) ![image](https://user-images.githubusercontent.com/50412488/150456422-97af1ae8-1264-47ad-8687-cb68bdd82205.png)

![image](https://user-images.githubusercontent.com/50412488/150456630-864a6276-8f06-415d-99c0-7fa15bce0a47.png)

**Comment by LianKaFoHaLi** [comment]
![image](https://user-images.githubusercontent.com/50412488/150461078-ef80f197-a1cd-4a6a-bd19-33d45f042467.png)
![image](https://user-images.githubusercontent.com/50412488/150461155-6a6c5d2f-6da4-4512-9641-3e4a209dd156.png)
The start row pos and end row pos is also limited.

**Comment by kisvegabor** [comment]
@LianKaFoHaLi 

How did you initialize the display driver? Please copy/paste including the display buffer size an initialization.

(Please send the code not an image to make it easy to copy into my project.)

**Comment by glin00** [comment]
@kisvegabor 
I used the rounder_cb to make x0 and y0 and x_width and y_width even numbers.  Then this problem is solved. 
Thank you for your support.

**Comment by LianKaFoHaLi** [comment]
Thank you for your reply,the following is lv_port_disp.c file and description.  

To solve this problem ,I define another full  screen size buffer in oled driver,when refresh area don't meet the requirement,I called 'oled_write_buf()' function that write data into another screen size buffer and complement data to fit the requirement,then use spi dma send data to screen.if refresh area fit the requirement,called 'oled_write_buf_refresh()' function that write data into another screen size buffer,meanwhile use spi dma send data to screen. 
because of 'my_rounder_cb' function added,above  90% refresh events are fit the requirement. But it's cost too many ram resources to define another full screen size buffer.
I still want to do some measure that make the lvgl refresh area fit the oled requirement  in 'disp_flush()' function.
`/**
 * @file lv_port_disp_templ.c
 *
 */

 /*Copy this file as "lv_port_disp.c" and set this value to "1" to enable content*/
#if 1

/*********************
 *      INCLUDES
 *********************/
#include "lv_port_disp.h"
#include "lvgl.h"
// #include "userdef.h"
/*********************
 *      DEFINES
 *********************/
#define MY_DISP_HOR_RES 126
#define MY_DISP_VER_RES 294  

/**********************
 *      TYPEDEFS
 **********************/

/**********************
 *  STATIC PROTOTYPES
 **********************/
static void disp_init(void);

static void disp_flush(lv_disp_drv_t * disp_drv, const lv_area_t * area, lv_color_t * color_p);
//static void gpu_fill(lv_disp_drv_t * disp_drv, lv_color_t * dest_buf, lv_coord_t dest_width,
//        const lv_area_t * fill_area, lv_color_t color);

/**********************
 *  STATIC VARIABLES
 **********************/

/**********************
 *      MACROS
 **********************/

/**********************
 *   GLOBAL FUNCTIONS
 **********************/

void lv_port_disp_init(void)
{
    /*-------------------------
     * Initialize your display
     * -----------------------*/
    disp_init();

    /*-----------------------------
     * Create a buffer for drawing
     *----------------------------*/

    /**
     * LVGL requires a buffer where it internally draws the widgets.
     * Later this buffer will passed to your display driver's `flush_cb` to copy its content to your display.
     * The buffer has to be greater than 1 display row
     *
     * There are 3 buffering configurations:
     * 1. Create ONE buffer:
     *      LVGL will draw the display's content here and writes it to your display
     *
     * 2. Create TWO buffer:
     *      LVGL will draw the display's content to a buffer and writes it your display.
     *      You should use DMA to write the buffer's content to the display.
     *      It will enable LVGL to draw the next part of the screen to the other buffer while
     *      the data is being sent form the first buffer. It makes rendering and flushing parallel.
     *
     * 3. Double buffering
     *      Set 2 screens sized buffers and set disp_drv.full_refresh = 1.
     *      This way LVGL will always provide the whole rendered screen in `flush_cb`
     *      and you only need to change the frame buffer's address.
     */

    /* Example for 1) */
    static lv_disp_draw_buf_t draw_buf_dsc_1;
    static lv_color_t buf_1[MY_DISP_HOR_RES*120];                          /*A buffer for 10 rows*/
    lv_disp_draw_buf_init(&draw_buf_dsc_1, buf_1, NULL, MY_DISP_HOR_RES*120);   /*Initialize the display buffer*/

    /* Example for 2) */
    // static lv_disp_draw_buf_t draw_buf_dsc_2;
    // static lv_color_t buf_2_1[MY_DISP_HOR_RES * 60];                        /*A buffer for 10 rows*/
    // static lv_color_t buf_2_2[MY_DISP_HOR_RES * 60];                        /*An other buffer for 10 rows*/
    // lv_disp_draw_buf_init(&draw_buf_dsc_2, buf_2_1, buf_2_2, MY_DISP_HOR_RES * 60);   /*Initialize the display buffer*/

    /* Example for 3) also set disp_drv.full_refresh = 1 below*/
    // static lv_disp_draw_buf_t draw_buf_dsc_3;
    // static lv_color_t buf_3_1[MY_DISP_HOR_RES * MY_DISP_VER_RES];            /*A screen sized buffer*/
    // static lv_color_t buf_3_2[MY_DISP_HOR_RES * MY_DISP_VER_RES];            /*An other screen sized buffer*/
    // lv_disp_draw_buf_init(&draw_buf_dsc_3, buf_3_1, buf_3_2, MY_DISP_HOR_RES * MY_DISP_VER_RES );   /*Initialize the display buffer*/

    /*-----------------------------------
     * Register the display in LVGL
     *----------------------------------*/

    static lv_disp_drv_t disp_drv;                         /*Descriptor of a display driver*/
    lv_disp_drv_init(&disp_drv);                    /*Basic initialization*/

    /*Set up the functions to access to your display*/

    /*Set the resolution of the display*/
    disp_drv.hor_res = 126;
    disp_drv.ver_res = 294;

    /*Used to copy the buffer's content to the display*/
    disp_drv.flush_cb = disp_flush;

    /*Set the screen Rotation*/
    disp_drv.sw_rotate=1;
    disp_drv.rotated=LV_DISP_ROT_90;

    /*Set a display buffer*/
    disp_drv.draw_buf = &draw_buf_dsc_1;

    disp_drv.rounder_cb = my_rounder_cb;
    /*Required for Example 3)*/
    // disp_drv.full_refresh = 1;

    /* Fill a memory array with a color if you have GPU.
     * Note that, in lv_conf.h you can enable GPUs that has built-in support in LVGL.
     * But if you have a different GPU you can use with this callback.*/
    //disp_drv.gpu_fill_cb = gpu_fill;

    /*Finally register the driver*/
    lv_disp_drv_register(&disp_drv);
}

/**********************
 *   STATIC FUNCTIONS
 **********************/

/*Initialize your display and the required peripherals.*/
static void disp_init(void)
{
    /*You code here*/
    oled_Init();
}

/*Flush the content of the internal buffer the specific area on the display
 *You can use DMA or any hardware acceleration to do this operation in the background but
 *'lv_disp_flush_ready()' has to be called when finished.*/
static void disp_flush(lv_disp_drv_t * disp_drv, const lv_area_t * area, lv_color_t * color_p)
{
    /*The most simple case (but also the slowest) to put all pixels to the screen one-by-one*/

    // int32_t x;
    // int32_t y;
    // for(y = area->y1; y <= area->y2; y++) {
    //     for(x = area->x1; x <= area->x2; x++) {
    //         /*Put a pixel to the display. For example:*/
    //         /*put_px(x, y, *color_p)*/
    //         color_p++;
    //     }
    // }
    if((area->x1%2!=0||area->y1%2!=0)||(area->x2%2!=1||area->y2%2!=1)){
        oled_write_buf(area->x1,area->y1,area->x2,area->y2,(oled_color16_t*)color_p,disp_drv);
        // lv_disp_flush_ready(disp_drv);
    }else{
        oled_write_buf_refresh(area->x1,area->y1,area->x2,area->y2,(oled_color16_t*)color_p,disp_drv);
    }
    // oled_Write_color(area->x1,area->y1,area->x2,area->y2,(oled_color16_t*)color_p);
    // oled_Write_Color_Dma(area->x1,area->y1,area->x2,area->y2,(oled_color16_t*)color_p,disp_drv);
    // oled_write_buf(area->x1,area->y1,area->x2,area->y2,(oled_color16_t*)color_p,disp_drv);
    // oled_write_buf_dma(area->x1,area->y1,area->x2,area->y2,(oled_color16_t*)color_p,disp_drv);
    /*IMPORTANT!!!
     *Inform the graphics library that you are ready with the flushing*/
    // lv_disp_flush_ready(disp_drv);
}

/*OPTIONAL: GPU INTERFACE*/

/*If your MCU has hardware accelerator (GPU) then you can use it to fill a memory with a color*/
//static void gpu_fill(lv_disp_drv_t * disp_drv, lv_color_t * dest_buf, lv_coord_t dest_width,
//                    const lv_area_t * fill_area, lv_color_t color)
//{
//    /*It's an example code which should be done by your GPU*/
//    int32_t x, y;
//    dest_buf += dest_width * fill_area->y1; /*Go to the first line*/
//
//    for(y = fill_area->y1; y <= fill_area->y2; y++) {
//        for(x = fill_area->x1; x <= fill_area->x2; x++) {
//            dest_buf[x] = color;
//        }
//        dest_buf+=dest_width;    /*Go to the next line*/
//    }
//}
void my_rounder_cb(struct _lv_disp_drv_t * disp_drv, lv_area_t * area){

    area->x1 = (area->x1/2)*2;
    area->y1 = (area->y1/2)*2;
    area->x2 = (area->x2/2)*2+1;
    area->y2 = (area->y2/2)*2+1;
}

#else /*Enable this file at the top*/

/*This dummy typedef exists purely to silence -Wpedantic.*/
typedef int keep_pedantic_happy;
#endif`

**Comment by LianKaFoHaLi** [comment]
> @kisvegabor I used the rounder_cb to make x0 and y0 and x_width and y_width even numbers. Then this problem is solved. Thank you for your support.
Hi, I also meet the same problem,but in some case the refresh area still don't fit the requirement.
