### ISSUE TITLE
`lv_draw_sw_rotate()` opposite of `lv_draw_pxp_rotate()`

### ISSUE THREAD

**Issue by kschwan** [kisvegabor/lvgl#6875]
### LVGL version

v9.2.0-58-g1dd63c7e5

### What happened?

Somewhere between release/v9.1 and master (1dd63c7e5) `lv_draw_sw_rotate()` started rotating the opposite direction of `lv_draw_pxp_rotate()`- Ie., if I rotate a buffer 90 deg, `lv_draw_sw_rotate()` is flipped compared to `lv_draw_pxp_rotate()`. It's not the case on release/v9.1.

**Comment by kisvegabor** [comment]
We have really discovered some misalignment recently. Now `lv_draw_sw_rotate()` and `lv_display_rotate_area()` are thinking the same way. 

cc @nicusorcitu

**Comment by nicusorcitu** [comment]
@cosmindanielradu19

**Comment by cosmindanielradu19** [comment]
I've seen that in SW, all the rotate90_X functions are rotating at 270 degrees, and rotate270_X functions are rotating at 90 degrees.

**Comment by nicusorcitu** [comment]
See also https://github.com/lvgl/lvgl/issues/6885

**Comment by kisvegabor** [comment]
>  I've seen that in SW, all the rotate90_X functions are rotating at 270 degrees, and rotate270_X functions are rotating at 90 degrees.

How do we know which is the correct direction?

**Comment by cosmindanielradu19** [comment]
> > I've seen that in SW, all the rotate90_X functions are rotating at 270 degrees, and rotate270_X functions are rotating at 90 degrees.
> 
> How do we know which is the correct direction?

I compared the output with PXP rotation and one is clockwise the other one is counterclockwise

**Comment by kschwan** [comment]
> > I've seen that in SW, all the rotate90_X functions are rotating at 270 degrees, and rotate270_X functions are rotating at 90 degrees.
> 
> How do we know which is the correct direction?

Looks like `lv_draw_sw_rotate()` changed while `lv_draw_pxp_rotate()` stayed the same

**Comment by liamHowatt** [comment]
`lv_draw_sw_rotate` was clockwise in v9.1 and now it is counterclockwise in master. It changed in this PR: #5703

Clockwise is more intuitive but counterclockwise is more correct in my opinion.

**Comment by cosmindanielradu19** [comment]
> `lv_draw_sw_rotate` was clockwise in v9.1 and now it is counterclockwise in master. It changed in this PR: #5703
> 
> Clockwise is more intuitive but counterclockwise is more correct in my opinion.

I believe that all the draw units should rotate in the same direction because it might be confusing at some point if you are doing development with CPU, then you want to use a board with PXP, and suddenly your display is upside down.

**Comment by kisvegabor** [comment]
Absolutely. As none of the directions are better let's use the SW render as a reference.

**Comment by kisvegabor** [comment]
It is already fixed in PXP, right?

**Comment by nicusorcitu** [comment]
No, not in this release. The PXP rotation have not changed in 9.2.1.

**Comment by nicusorcitu** [comment]
@cosmindanielradu19 please prepare a patch to sync PXP with CPU and create a PR upstream to be integrated to 9.2.1 as well.
We need to keep the consistency.

**Comment by cosmindanielradu19** [comment]
I've created a PR with the patch

#7063

**Comment by liamHowatt** [comment]
Fixed by #7063

**Comment by kschwan** [comment]
#7063 was merged into release/v9.2, but not master. So the issue persists on master

@liamHowatt, @cosmindanielradu19

**Comment by cosmindanielradu19** [comment]
@kisvegabor do you mind if I'm adding this to #8156 ?

**Comment by nicusorcitu** [comment]
Please do it - the change is harmless for any others except PXP users.
