### ISSUE TITLE
Docs: Some examples not rendering because web version is not compiled with optional flags

### ISSUE THREAD

**Issue by timonsku** [kisvegabor/lvgl#7501]
### LVGL version

v9.2.0

### Platform

Web

### What happened?

Some of the examples that use new optional features like complex gradient are not rendering in the documentation page as the release was not compiled with those optional features enabled.

### How to reproduce?

Visit https://docs.lvgl.io/9.2/examples.html#radial-gradient-as-background a warning is shown instead of rendering the examples as expected.

**Comment by timonsku** [comment]
still relevant

**Comment by kisvegabor** [comment]
Our docs page is down for some unknown reasons, so I can't check it now. 😟

IIRC correctly I'v already fixed in in master.

**Comment by timonsku** [comment]
Seems to be back online, still showing the warning that the feature is not enabled

**Comment by timonsku** [comment]
DRAW_TRANSFORM_USE_MATRIX is still disabled for Master too though
https://docs.lvgl.io/master/examples.html#transform-object-using-a-3x3-matrix

**Comment by timonsku** [comment]
still relevant

**Comment by liamHowatt** [comment]
I think we can enable some of these. `USE_DRAW_SW_COMPLEX_GRADIENTS` should be completely fine to enable, I think. Any others?

I have one concern. `TRANSFORM_USE_MATRIX` is kind of experimental. If something indirectly causes matrix-based transformation to regress, all examples that use transformations will break. The examples in the docs all come from the same Emscripten object so all examples share the same configurations.
